variables:
  DOCKER_HOST: tcp://docker:2375
  DOCKER_DRIVER: overlay2
  DOCKER_TLS_CERTDIR: ""

stages:
  - build
  - deploy

build:
  stage: build
  image: docker:latest
  only:
    - master
  services:
    - docker:dind
  before_script:
    - apk add --no-cache curl jq python3 py3-pip py3-virtualenv
    - python3 -m venv /app/venv
    - . /app/venv/bin/activate && pip install awscli
    - . /app/venv/bin/activate && aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin $DOCKER_REGISTRY
  script:
    - . /app/venv/bin/activate && docker build -t $DOCKER_REGISTRY:version-1.0.$CI_PIPELINE_IID .
    - . /app/venv/bin/activate && docker push $DOCKER_REGISTRY:version-1.0.$CI_PIPELINE_IID
    - . /app/venv/bin/activate && docker tag $DOCKER_REGISTRY:version-1.0.$CI_PIPELINE_IID $DOCKER_REGISTRY:latest
    - . /app/venv/bin/activate && docker push $DOCKER_REGISTRY:latest

deploy:
  stage: deploy
  image: docker:latest
  only:
    - master
  before_script:
    - 'command -v ssh-agent >/dev/null || ( apt-get update -y && apt-get install openssh-client -y )'
    - eval $(ssh-agent -s)
    - echo "$ssh" | tr -d '\r' | ssh-add -
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
  script:
    - ssh -o StrictHostKeyChecking=no ec2-user@54.91.36.145 './deploy.sh'
